### ISSUE TITLE
parseToken 时候没有验证过期?

### ISSUE THREAD

**Issue by Denny-w** [imiphp/imi-jwt#1]
填写了过期时间，过期了仍然能解析出来，源码中解析没看到验证过期时间

**Comment by Yurunsoft** [comment]
非常感谢，目前只验证了 jwt 是否合法，晚点会支持对 jwt 中数据进行验证

**Comment by Denny-w** [comment]
还有刷新token的方法

**Comment by Yurunsoft** [comment]
刷新token就是重新生成。

jwt一旦生成里面数据是不能更改，只能重新生成一个新的token
